#!/usr/bin/env python3
"""
Generate Vietnamese translations for vocabulary entry-batches.
Reads entry-batch-NNNNN.json files and writes translated/batch-NNNNN.json.

Usage:
  python3 scripts/generate/generate-vocabulary-vi-local.py [start] [end]
  python3 scripts/generate/generate-vocabulary-vi-local.py         # all remaining
  python3 scripts/generate/generate-vocabulary-vi-local.py 136 200 # batches 136-200
"""

import json
import os
import re
import sys
import glob

ENTRY_DIR  = "data/vocabulary-vi/entry-batches"
OUTPUT_DIR = "data/vocabulary-vi/translated"

# ---------------------------------------------------------------------------
# English → Vietnamese core dictionary
# Covers the most frequent meanings found in JMDict.
# Values: Vietnamese meaning (concise, as used in meaning_vi field).
# ---------------------------------------------------------------------------
EN_VI: dict[str, str] = {
    # ------ adverbs / degree ------
    "extremely": "cực kỳ",
    "very": "rất",
    "completely": "hoàn toàn",
    "entirely": "hoàn toàn",
    "thoroughly": "triệt để",
    "absolutely": "tuyệt đối",
    "totally": "hoàn toàn",
    "truly": "thật sự",
    "really": "thực sự",
    "certainly": "chắc chắn",
    "exactly": "chính xác",
    "indeed": "thật vậy",
    "just": "chỉ; vừa",
    "still": "vẫn",
    "soon": "sớm",
    "quickly": "nhanh chóng",
    "rapidly": "nhanh chóng",
    "slowly": "chậm rãi",
    "gradually": "dần dần",
    "suddenly": "đột nhiên",
    "immediately": "ngay lập tức",
    "unexpectedly": "bất ngờ",
    "easily": "dễ dàng",
    "smoothly": "suôn sẻ",
    "quietly": "yên lặng",
    "firmly": "vững chắc",
    "tightly": "chặt chẽ",
    "closely": "chặt chẽ; gần gũi",
    "clearly": "rõ ràng",
    "vigorously": "mạnh mẽ",
    "steadily": "đều đặn",
    "hard": "chăm chỉ; cứng",
    "well": "tốt",
    "often": "thường xuyên",
    "perhaps": "có lẽ",
    "possibly": "có thể",
    "already": "đã",
    "once": "một lần; từng",
    "always": "luôn luôn",
    "never": "không bao giờ",
    "sometimes": "đôi khi",
    "together": "cùng nhau",
    "even": "thậm chí",
    "however": "tuy nhiên",
    "although": "mặc dù",
    "since": "từ khi; vì",
    "recently": "gần đây",
    "finally": "cuối cùng",
    "in the end": "cuối cùng",
    "after all": "xét cho cùng",
    "at last": "cuối cùng",
    "at once": "ngay lập tức",
    "by all means": "bằng mọi cách",
    "not at all": "không chút nào",
    "(not) at all": "hoàn toàn không",
    "for a long time": "trong thời gian dài",
    "like that": "như vậy",

    # ------ common verbs ------
    "to be": "là; tồn tại",
    "to do": "làm; thực hiện",
    "to go": "đi",
    "to come": "đến",
    "to get": "lấy; nhận được",
    "to give": "cho; đưa",
    "to take": "lấy; mang",
    "to make": "làm; tạo ra",
    "to put": "đặt; để",
    "to have": "có",
    "to see": "nhìn thấy; gặp",
    "to look": "nhìn; trông",
    "to know": "biết",
    "to think": "nghĩ",
    "to say": "nói",
    "to tell": "kể; bảo",
    "to ask": "hỏi",
    "to want": "muốn",
    "to use": "sử dụng",
    "to work": "làm việc",
    "to live": "sống",
    "to die": "chết",
    "to eat": "ăn",
    "to drink": "uống",
    "to sleep": "ngủ",
    "to wake": "thức dậy",
    "to stand": "đứng",
    "to sit": "ngồi",
    "to walk": "đi bộ",
    "to run": "chạy",
    "to move": "di chuyển",
    "to stop": "dừng",
    "to start": "bắt đầu",
    "to begin": "bắt đầu",
    "to end": "kết thúc",
    "to finish": "hoàn thành",
    "to open": "mở",
    "to close": "đóng",
    "to read": "đọc",
    "to write": "viết",
    "to speak": "nói",
    "to listen": "nghe",
    "to hear": "nghe thấy",
    "to buy": "mua",
    "to sell": "bán",
    "to send": "gửi",
    "to receive": "nhận",
    "to hold": "cầm; giữ",
    "to carry": "mang; vác",
    "to pull": "kéo",
    "to push": "đẩy",
    "to cut": "cắt",
    "to break": "phá vỡ",
    "to build": "xây dựng",
    "to make": "làm; tạo",
    "to create": "tạo ra",
    "to change": "thay đổi",
    "to turn": "xoay; rẽ",
    "to return": "trở về; trả lại",
    "to bring": "mang lại",
    "to leave": "rời đi; để lại",
    "to enter": "vào",
    "to exit": "ra",
    "to arrive": "đến nơi",
    "to pass": "vượt qua; đi qua",
    "to cross": "băng qua",
    "to follow": "theo; đi theo",
    "to lead": "dẫn dắt",
    "to show": "cho thấy; chỉ",
    "to play": "chơi",
    "to win": "thắng",
    "to lose": "thua; mất",
    "to help": "giúp đỡ",
    "to support": "hỗ trợ",
    "to protect": "bảo vệ",
    "to attack": "tấn công",
    "to fight": "chiến đấu",
    "to escape": "trốn thoát",
    "to catch": "bắt",
    "to throw": "ném",
    "to hit": "đánh; đập",
    "to kill": "giết",
    "to save": "cứu; tiết kiệm",
    "to lose": "thua; mất",
    "to find": "tìm thấy",
    "to search": "tìm kiếm",
    "to meet": "gặp",
    "to call": "gọi",
    "to answer": "trả lời",
    "to wait": "đợi",
    "to try": "thử",
    "to decide": "quyết định",
    "to choose": "chọn",
    "to accept": "chấp nhận",
    "to refuse": "từ chối",
    "to agree": "đồng ý",
    "to deny": "phủ nhận",
    "to forget": "quên",
    "to remember": "nhớ",
    "to learn": "học",
    "to teach": "dạy",
    "to study": "học; nghiên cứu",
    "to understand": "hiểu",
    "to explain": "giải thích",
    "to think about": "suy nghĩ về",
    "to worry": "lo lắng",
    "to fear": "sợ",
    "to trust": "tin tưởng",
    "to love": "yêu",
    "to like": "thích",
    "to hate": "ghét",
    "to enjoy": "thích thú",
    "to laugh": "cười",
    "to cry": "khóc",
    "to smile": "mỉm cười",
    "to feel": "cảm thấy",
    "to become": "trở thành",
    "to grow": "phát triển; lớn lên",
    "to increase": "tăng",
    "to decrease": "giảm",
    "to improve": "cải thiện",
    "to decline": "suy giảm",
    "to fall": "ngã; rơi",
    "to rise": "nổi lên; tăng",
    "to get up": "thức dậy",
    "to lie down": "nằm xuống",
    "to appear": "xuất hiện",
    "to disappear": "biến mất",
    "to exist": "tồn tại",
    "to happen": "xảy ra",
    "to occur": "xảy ra",
    "to continue": "tiếp tục",
    "to repeat": "lặp lại",
    "to prepare": "chuẩn bị",
    "to plan": "lên kế hoạch",
    "to manage": "quản lý; xoay xở",
    "to control": "kiểm soát",
    "to handle": "xử lý; cầm",
    "to solve": "giải quyết",
    "to fix": "sửa chữa",
    "to clean": "làm sạch",
    "to wash": "rửa; giặt",
    "to cook": "nấu ăn",
    "to eat and drink": "ăn uống",
    "to think": "nghĩ; suy nghĩ",
    "to consider": "cân nhắc",
    "to notice": "nhận thấy",
    "to remember": "nhớ",
    "to imagine": "tưởng tượng",
    "to believe": "tin",
    "to admit": "thừa nhận",
    "to abandon": "từ bỏ; bỏ rơi",
    "to give up": "từ bỏ",
    "to do one's best": "cố gắng hết sức",

    # ------ common nouns ------
    "person": "người",
    "man": "đàn ông",
    "woman": "phụ nữ",
    "child": "đứa trẻ",
    "people": "mọi người",
    "friend": "bạn bè",
    "companion": "bạn đồng hành",
    "follower": "người theo dõi",
    "attendant": "nhân viên phục vụ",
    "master": "bậc thầy; chủ nhân",
    "leader": "thủ lĩnh; lãnh đạo",
    "chief": "trưởng; thủ lĩnh",
    "manager": "quản lý; giám đốc",
    "teacher": "giáo viên",
    "student": "học sinh",
    "father": "cha",
    "mother": "mẹ",
    "parent": "cha mẹ",
    "child (one's own)": "con",
    "son": "con trai",
    "daughter": "con gái",
    "brother": "anh; em trai",
    "sister": "chị; em gái",
    "husband": "chồng",
    "wife": "vợ",
    "family": "gia đình",
    "ancestor": "tổ tiên",
    "descendant": "con cháu",
    "enemy": "kẻ thù",
    "stranger": "người lạ",
    "fool": "kẻ ngốc",
    "idiot": "kẻ ngốc",
    "prostitute": "gái mại dâm",
    "ghost": "ma; hồn ma",
    "god": "thần; thượng đế",
    "time": "thời gian",
    "moment": "khoảnh khắc",
    "instant": "tức thì",
    "day": "ngày",
    "night": "đêm",
    "morning": "buổi sáng",
    "evening": "buổi tối",
    "year": "năm",
    "month": "tháng",
    "week": "tuần",
    "hour": "giờ",
    "minute": "phút",
    "second": "giây",
    "period": "thời kỳ",
    "season": "mùa",
    "future": "tương lai",
    "past": "quá khứ",
    "present": "hiện tại",
    "eternity": "vĩnh cửu",
    "place": "nơi chốn",
    "space": "không gian",
    "area": "khu vực",
    "country": "đất nước",
    "city": "thành phố",
    "town": "thị trấn",
    "village": "làng",
    "Japan": "Nhật Bản",
    "road": "con đường",
    "way": "cách; con đường",
    "path": "lối đi",
    "house": "nhà",
    "home": "ngôi nhà; quê hương",
    "room": "phòng",
    "shop": "cửa hàng",
    "school": "trường học",
    "company": "công ty",
    "office": "văn phòng",
    "government": "chính phủ",
    "water": "nước",
    "fire": "lửa",
    "air": "không khí",
    "wind": "gió",
    "earth": "đất",
    "sky": "bầu trời",
    "sea": "biển",
    "mountain": "núi",
    "tree": "cây",
    "flower": "hoa",
    "grass": "cỏ",
    "animal": "động vật",
    "bird": "chim",
    "fish": "cá",
    "food": "thức ăn",
    "meal": "bữa ăn",
    "money": "tiền",
    "price": "giá cả",
    "work": "công việc",
    "job": "nghề nghiệp; công việc",
    "business": "kinh doanh",
    "matter": "vấn đề",
    "thing": "thứ; vật",
    "item": "vật phẩm",
    "object": "đồ vật",
    "tool": "công cụ",
    "machine": "máy móc",
    "car": "xe hơi",
    "vehicle": "phương tiện",
    "ship": "tàu thuyền",
    "boat": "thuyền",
    "train": "tàu hỏa",
    "airplane": "máy bay",
    "book": "sách",
    "letter": "bức thư; chữ cái",
    "word": "từ; từ ngữ",
    "language": "ngôn ngữ",
    "name": "tên",
    "number": "con số",
    "color": "màu sắc",
    "shape": "hình dạng",
    "size": "kích cỡ",
    "head": "đầu",
    "face": "khuôn mặt",
    "eye": "mắt",
    "ear": "tai",
    "nose": "mũi",
    "mouth": "miệng",
    "hand": "bàn tay",
    "foot": "bàn chân",
    "body": "cơ thể",
    "heart": "trái tim",
    "mind": "tâm trí",
    "soul": "linh hồn",
    "spirit": "tinh thần",
    "nature": "tự nhiên; bản chất",
    "character": "tính cách; nhân vật",
    "feeling": "cảm giác",
    "mood": "tâm trạng",
    "voice": "giọng nói",
    "sound": "âm thanh",
    "light": "ánh sáng",
    "color": "màu sắc",
    "heat": "nhiệt",
    "pain": "đau đớn",
    "strength": "sức mạnh",
    "power": "sức mạnh; quyền lực",
    "skill": "kỹ năng",
    "ability": "khả năng",
    "knowledge": "kiến thức",
    "wisdom": "trí tuệ",
    "love": "tình yêu",
    "hate": "sự thù ghét",
    "fear": "nỗi sợ",
    "joy": "niềm vui",
    "sadness": "nỗi buồn",
    "anger": "sự tức giận",
    "surprise": "sự ngạc nhiên",
    "hope": "hy vọng",
    "dream": "giấc mơ",
    "thought": "suy nghĩ",
    "idea": "ý tưởng",
    "plan": "kế hoạch",
    "rule": "quy tắc",
    "law": "luật",
    "order": "trật tự; mệnh lệnh",
    "freedom": "tự do",
    "truth": "sự thật",
    "lie": "lời nói dối",
    "fact": "sự thật; thực tế",
    "reason": "lý do",
    "result": "kết quả",
    "effect": "hiệu quả",
    "cause": "nguyên nhân",
    "beginning": "khởi đầu; ban đầu",
    "start": "bắt đầu; khởi đầu",
    "end": "kết thúc; cuối",
    "middle": "giữa; trung tâm",
    "part": "phần",
    "whole": "toàn bộ",
    "group": "nhóm",
    "section": "bộ phận; tiết",
    "side": "phía; cạnh",
    "front": "phía trước; mặt trước",
    "back": "phía sau; lưng",
    "top": "đỉnh; trên cùng",
    "bottom": "đáy; phía dưới",
    "inside": "bên trong",
    "outside": "bên ngoài",
    "origin": "nguồn gốc; xuất xứ",
    "source": "nguồn",
    "base": "nền tảng; cơ sở",
    "foundation": "nền tảng",
    "conclusion": "kết luận",
    "summary": "tóm tắt",
    "outline": "phác thảo; tóm lược",
    "example": "ví dụ",
    "case": "trường hợp",
    "type": "loại; kiểu",
    "kind": "loại; tử tế",
    "form": "hình thức",
    "method": "phương pháp",
    "means": "phương tiện",
    "way": "cách",
    "measure": "biện pháp",
    "system": "hệ thống",
    "process": "quá trình",
    "condition": "điều kiện; tình trạng",
    "state": "trạng thái",
    "situation": "tình huống",
    "circumstances": "hoàn cảnh",
    "matter": "vấn đề",
    "problem": "vấn đề; bài toán",
    "question": "câu hỏi; vấn đề",
    "answer": "câu trả lời",
    "solution": "giải pháp",
    "result": "kết quả",
    "success": "thành công",
    "failure": "thất bại",
    "mistake": "lỗi; sai lầm",
    "fault": "lỗi; tội",
    "trouble": "rắc rối; phiền não",
    "confusion": "sự nhầm lẫn",
    "disorder": "rối loạn",
    "chance": "cơ hội; may mắn",
    "luck": "may mắn",
    "fortune": "vận may; tài sản",
    "risk": "rủi ro",
    "danger": "nguy hiểm",
    "safety": "sự an toàn",
    "benefit": "lợi ích",
    "advantage": "lợi thế",
    "loss": "sự mất mát; thua lỗ",
    "damage": "thiệt hại",
    "help": "sự giúp đỡ",
    "assistance": "sự hỗ trợ",
    "service": "dịch vụ",
    "support": "hỗ trợ",
    "training": "huấn luyện",
    "education": "giáo dục",
    "practice": "thực hành",
    "experience": "kinh nghiệm",
    "talent": "tài năng",
    "gift": "quà tặng; tài năng",
    "reward": "phần thưởng",
    "punishment": "hình phạt",
    "agreement": "thỏa thuận",
    "discussion": "thảo luận",
    "introduction": "lời giới thiệu",
    "connection": "kết nối; mối quan hệ",
    "relationship": "mối quan hệ",
    "position": "vị trí; chức vụ",
    "role": "vai trò",
    "function": "chức năng",
    "purpose": "mục đích",
    "goal": "mục tiêu",
    "standard": "tiêu chuẩn",
    "level": "mức độ; cấp độ",
    "quality": "chất lượng",
    "value": "giá trị",
    "price": "giá cả",
    "charge": "phí; trách nhiệm",
    "cost": "chi phí",
    "amount": "số lượng",
    "number": "con số",
    "figure": "hình dáng; con số",
    "mark": "dấu; điểm",
    "sign": "dấu hiệu; biển",
    "symbol": "biểu tượng",
    "image": "hình ảnh",
    "appearance": "ngoại hình; vẻ ngoài",
    "looks": "ngoại hình",
    "color": "màu sắc",
    "pattern": "hình mẫu; mẫu",
    "sample": "mẫu",
    "model": "mô hình; mẫu",
    "style": "phong cách",
    "fashion": "thời trang",
    "custom": "phong tục; thói quen",
    "culture": "văn hóa",
    "tradition": "truyền thống",
    "art": "nghệ thuật",
    "music": "âm nhạc",
    "song": "bài hát",
    "story": "câu chuyện",
    "plot": "cốt truyện",
    "character": "nhân vật",
    "scene": "cảnh; khung cảnh",
    "drama": "kịch; bi kịch",
    "comedy": "hài kịch",
    "game": "trò chơi",
    "competition": "cuộc thi; cạnh tranh",
    "match": "trận đấu",
    "team": "đội",
    "sport": "thể thao",
    "hobby": "sở thích",
    "entertainment": "giải trí",
    "event": "sự kiện",
    "ceremony": "lễ nghi; buổi lễ",
    "festival": "lễ hội",
    "celebration": "sự ăn mừng",
    "reward": "phần thưởng",
    "honor": "danh dự",
    "fame": "danh tiếng",
    "glory": "vinh quang",
    "shame": "sự xấu hổ",
    "honor": "danh dự",
    "truth": "sự thật",
    "fact": "thực tế",
    "opinion": "ý kiến",
    "information": "thông tin",
    "news": "tin tức",
    "report": "báo cáo",
    "announcement": "thông báo",
    "message": "thông điệp",
    "letter": "bức thư",
    "contract": "hợp đồng",
    "document": "tài liệu",
    "record": "hồ sơ; kỷ lục",
    "note": "ghi chú",
    "list": "danh sách",
    "exam": "kỳ thi",
    "test": "bài kiểm tra",
    "question": "câu hỏi",
    "answer": "câu trả lời",
    "excuse": "lý do; bào chữa",
    "apology": "lời xin lỗi",
    "complaint": "lời phàn nàn",
    "request": "yêu cầu",
    "demand": "nhu cầu; đòi hỏi",
    "promise": "lời hứa",
    "warning": "cảnh báo",
    "threat": "lời đe dọa",
    "secret": "bí mật",
    "rumor": "tin đồn",
    "joke": "trò đùa",
    "praise": "sự khen ngợi",
    "flattery": "sự nịnh hót",
    "criticism": "sự chỉ trích",
    "judgment": "phán xét",
    "judgement": "sự đánh giá",
    "decision": "quyết định",
    "selection": "lựa chọn",
    "consideration": "sự cân nhắc",
    "understanding": "sự hiểu biết",
    "influence": "ảnh hưởng",
    "effect": "tác động",
    "impact": "tác động",
    "weight": "trọng lượng; tầm quan trọng",
    "importance": "tầm quan trọng",
    "meaning": "ý nghĩa",
    "sense": "ý nghĩa; cảm giác",
    "point": "điểm; ý nghĩa",
    "tip": "mẹo; đầu",
    "hint": "gợi ý",
    "guide": "hướng dẫn",
    "direction": "hướng",
    "instruction": "hướng dẫn; chỉ thị",
    "explanation": "giải thích",
    "description": "mô tả",
    "definition": "định nghĩa",
    "detail": "chi tiết",
    "information": "thông tin",
    "evidence": "bằng chứng",
    "proof": "bằng chứng",
    "test": "kiểm tra",
    "investigation": "điều tra",
    "research": "nghiên cứu",
    "study": "nghiên cứu",
    "analysis": "phân tích",
    "theory": "lý thuyết",
    "principle": "nguyên tắc",
    "rule": "quy tắc",
    "regulation": "quy định",
    "law": "luật",
    "policy": "chính sách",
    "permission": "sự cho phép",
    "right": "quyền",
    "duty": "nghĩa vụ",
    "responsibility": "trách nhiệm",
    "authority": "quyền lực; chính quyền",
    "power": "quyền lực; sức mạnh",
    "force": "lực lượng; cưỡng bức",
    "energy": "năng lượng",
    "effort": "nỗ lực",
    "strength": "sức mạnh",
    "weakness": "điểm yếu",
    "ability": "khả năng",
    "capacity": "năng lực",
    "potential": "tiềm năng",
    "talent": "tài năng",
    "skill": "kỹ năng",
    "technique": "kỹ thuật",
    "method": "phương pháp",
    "procedure": "thủ tục",
    "step": "bước",
    "stage": "giai đoạn",
    "phase": "giai đoạn",
    "level": "cấp độ",
    "degree": "mức độ",
    "extent": "phạm vi",
    "limit": "giới hạn",
    "boundary": "ranh giới",
    "range": "phạm vi",
    "area": "khu vực",
    "zone": "vùng",
    "field": "lĩnh vực",
    "domain": "lĩnh vực",
    "subject": "chủ đề; môn học",
    "topic": "chủ đề",
    "theme": "chủ đề",
    "content": "nội dung",
    "material": "vật liệu; nội dung",
    "matter": "vật chất; vấn đề",
    "substance": "chất; thực chất",
    "element": "yếu tố",
    "component": "thành phần",
    "part": "phần",
    "piece": "mảnh",
    "set": "bộ",
    "collection": "bộ sưu tập",
    "stock": "kho; cổ phần",
    "supply": "nguồn cung",
    "provision": "cung cấp",
    "preparation": "sự chuẩn bị",
    "arrangement": "sắp xếp",
    "organization": "tổ chức",
    "structure": "cấu trúc",
    "construction": "xây dựng",
    "creation": "sự sáng tạo",
    "production": "sản xuất",
    "product": "sản phẩm",
    "goods": "hàng hóa",
    "item": "vật phẩm",
    "equipment": "thiết bị",
    "tool": "công cụ",
    "instrument": "nhạc cụ; dụng cụ",
    "machine": "máy",
    "device": "thiết bị",
    "computer": "máy tính",
    "phone": "điện thoại",
    "camera": "máy ảnh",
    "car": "xe hơi",
    "gas": "khí ga; xăng",
    "anchor": "neo",
    "service": "dịch vụ",
    "competition": "cạnh tranh",
    "guide number": "số hướng dẫn",
    "guidebook": "sách hướng dẫn",
    "guidepost": "cột mốc",
    "guidance": "hướng dẫn",
    "course": "khóa học; đường đi",
    "program": "chương trình",
    "project": "dự án",
    "work": "công việc",
    "task": "nhiệm vụ",
    "mission": "sứ mệnh",
    "duty": "nghĩa vụ",
    "role": "vai trò",
    "rank": "cấp bậc",
    "grade": "cấp; điểm",
    "class": "lớp; hạng",
    "category": "danh mục",
    "group": "nhóm",
    "party": "đảng; bữa tiệc",
    "society": "xã hội",
    "community": "cộng đồng",
    "nation": "quốc gia",
    "world": "thế giới",
    "universe": "vũ trụ",

    # ------ common adjectives ------
    "good": "tốt",
    "bad": "xấu; tệ",
    "big": "lớn; to",
    "large": "lớn",
    "small": "nhỏ",
    "little": "nhỏ; ít",
    "long": "dài",
    "short": "ngắn",
    "tall": "cao",
    "high": "cao",
    "low": "thấp",
    "wide": "rộng",
    "narrow": "hẹp",
    "thick": "dày",
    "thin": "mỏng",
    "heavy": "nặng",
    "light": "nhẹ",
    "hot": "nóng",
    "cold": "lạnh",
    "warm": "ấm",
    "cool": "mát",
    "new": "mới",
    "old": "cũ; già",
    "young": "trẻ",
    "ancient": "cổ đại",
    "modern": "hiện đại",
    "fast": "nhanh",
    "slow": "chậm",
    "easy": "dễ dàng",
    "difficult": "khó khăn",
    "hard": "khó; cứng",
    "soft": "mềm",
    "strong": "mạnh",
    "weak": "yếu",
    "rich": "giàu",
    "poor": "nghèo",
    "beautiful": "đẹp",
    "ugly": "xấu",
    "clean": "sạch",
    "dirty": "bẩn",
    "dark": "tối",
    "bright": "sáng",
    "clear": "rõ ràng",
    "vague": "mơ hồ",
    "simple": "đơn giản",
    "complex": "phức tạp",
    "ordinary": "bình thường",
    "special": "đặc biệt",
    "common": "thông thường; phổ biến",
    "rare": "hiếm",
    "usual": "thường xuyên",
    "unusual": "bất thường",
    "strange": "kỳ lạ",
    "familiar": "quen thuộc",
    "foreign": "nước ngoài",
    "local": "địa phương",
    "general": "chung; tổng quát",
    "specific": "cụ thể",
    "regular": "thường xuyên; đều đặn",
    "normal": "bình thường",
    "proper": "đúng đắn; thích hợp",
    "correct": "chính xác; đúng",
    "wrong": "sai",
    "true": "đúng; thật",
    "false": "sai; giả",
    "real": "thật",
    "fake": "giả",
    "original": "nguyên bản; độc đáo",
    "plain": "đơn giản; rõ ràng",
    "fine": "tốt; ổn",
    "pure": "trong sáng; thuần khiết",
    "honest": "thành thật; trung thực",
    "frank": "thẳng thắn",
    "humble": "khiêm tốn",
    "proud": "tự hào",
    "kind": "tử tế",
    "gentle": "nhẹ nhàng",
    "calm": "bình tĩnh",
    "quiet": "yên lặng",
    "peaceful": "hòa bình",
    "serious": "nghiêm trọng; nghiêm túc",
    "severe": "nghiêm khắc",
    "strict": "nghiêm khắc",
    "firm": "vững chắc; kiên định",
    "stable": "ổn định",
    "steady": "vững vàng",
    "safe": "an toàn",
    "dangerous": "nguy hiểm",
    "careful": "cẩn thận",
    "careless": "bất cẩn",
    "brave": "dũng cảm",
    "cowardly": "hèn nhát",
    "clever": "thông minh",
    "stupid": "ngốc nghếch",
    "foolish": "dại dột",
    "wise": "khôn ngoan",
    "smart": "thông minh",
    "talented": "tài năng",
    "skillful": "khéo léo",
    "lazy": "lười biếng",
    "hardworking": "chăm chỉ",
    "busy": "bận rộn",
    "free": "tự do; rảnh",
    "empty": "trống rỗng",
    "full": "đầy",
    "complete": "đầy đủ; hoàn chỉnh",
    "incomplete": "chưa hoàn chỉnh",
    "perfect": "hoàn hảo",
    "ideal": "lý tưởng",
    "excellent": "xuất sắc",
    "splendid": "tuyệt vời",
    "wonderful": "tuyệt vời",
    "terrible": "khủng khiếp",
    "awful": "tồi tệ",
    "useless": "vô dụng",
    "hopeless": "tuyệt vọng",
    "absurd": "vô lý",
    "ridiculous": "lố bịch",
    "extraordinary": "phi thường",
    "trivial": "tầm thường",
    "trifling": "nhỏ nhặt",
    "insignificant": "không đáng kể",
    "important": "quan trọng",
    "necessary": "cần thiết",
    "essential": "thiết yếu",
    "useful": "hữu ích",
    "effective": "hiệu quả",
    "efficient": "hiệu quả",
    "convenient": "tiện lợi",
    "comfortable": "thoải mái",
    "pleasant": "dễ chịu",
    "enjoyable": "thú vị",
    "boring": "nhàm chán",
    "dull": "nhàm chán; tẻ nhạt",
    "exciting": "thú vị",
    "interesting": "thú vị",
    "amusing": "vui nhộn",
    "funny": "buồn cười",
    "serious": "nghiêm túc",
    "formal": "trang trọng",
    "casual": "thân mật; bình thường",
    "polite": "lịch sự",
    "rude": "thô lỗ",
    "vulgar": "thô tục",
    "crude": "thô; thô lỗ",
    "rough": "thô; gồ ghề",
    "smooth": "mượt mà",
    "sharp": "sắc nét; nhọn",
    "blunt": "cùn; thẳng thắn",
    "flat": "phẳng",
    "round": "tròn",
    "straight": "thẳng",
    "curved": "cong",
    "open": "mở",
    "closed": "đóng",
    "visible": "có thể nhìn thấy",
    "hidden": "ẩn; bí mật",
    "secret": "bí mật",
    "public": "công cộng",
    "private": "riêng tư",
    "personal": "cá nhân",
    "social": "xã hội",
    "political": "chính trị",
    "economic": "kinh tế",
    "cultural": "văn hóa",
    "natural": "tự nhiên",
    "artificial": "nhân tạo",
    "manual": "thủ công",
    "automatic": "tự động",
    "main": "chính",
    "major": "lớn; chính yếu",
    "minor": "nhỏ; phụ",
    "primary": "cơ bản; chính",
    "secondary": "thứ hai; phụ",
    "additional": "bổ sung",
    "extra": "thêm",
    "temporary": "tạm thời",
    "permanent": "vĩnh viễn",
    "current": "hiện tại; hiện hành",
    "ancient": "cổ đại",
    "traditional": "truyền thống",
    "modern": "hiện đại",
    "western": "phương Tây",
    "eastern": "phương Đông",
    "japanese": "Nhật Bản",
    "chinese": "Trung Quốc",
    "english": "Anh; tiếng Anh",
    "stubborn": "bướng bỉnh",
    "determined": "kiên quyết",
    "flexible": "linh hoạt",
    "rigid": "cứng nhắc",
    "plump": "mũm mĩm",
    "graceful": "duyên dáng",
    "elegant": "thanh lịch",
    "charming": "hấp dẫn",
    "attractive": "thu hút",
    "gloomy": "ảm đạm",
    "cheerful": "vui vẻ",
    "lively": "sống động",
    "active": "năng động",
    "passive": "thụ động",
    "aggressive": "hung hăng",
    "timid": "nhút nhát",
    "hesitant": "do dự",
    "confident": "tự tin",
    "arrogant": "kiêu ngạo",
    "modest": "khiêm tốn",
    "sincere": "chân thành",
    "genuine": "thật; chân thực",
    "fake": "giả",
    "extreme": "cực đoan",
    "moderate": "vừa phải",
    "excessive": "quá mức",
    "sufficient": "đủ",
    "insufficient": "không đủ",
    "abundant": "phong phú",
    "scarce": "khan hiếm",
    "tight": "chặt",
    "loose": "lỏng",
    "dense": "đặc; dày đặc",
    "sparse": "thưa thớt",
    "deep": "sâu",
    "shallow": "nông",
    "loud": "to",
    "quiet": "yên tĩnh; im lặng",
    "silent": "im lặng",
    "noisy": "ồn ào",
    "cheerful": "vui vẻ",
    "happy": "hạnh phúc",
    "sad": "buồn",
    "angry": "tức giận",
    "surprised": "ngạc nhiên",
    "afraid": "sợ hãi",
    "ashamed": "xấu hổ",
    "proud": "tự hào",
    "grateful": "biết ơn",
    "lonely": "cô đơn",
    "restless": "bồn chồn",
    "impatient": "thiếu kiên nhẫn",
    "patient": "kiên nhẫn",
    "dawdling": "chần chừ",
    "frank": "thẳng thắn",

    # ------ compound nouns / specific terms ------
    "tour guide": "hướng dẫn viên du lịch",
    "guide ring": "vòng dẫn",
    "conductor": "nhạc trưởng; người điều khiển",
    "guiding": "dẫn đường; hướng dẫn",
    "leading": "dẫn đầu; chủ yếu",
    "direction": "hướng; chỉ đạo",
    "management": "quản lý",
    "administration": "hành chính; quản trị",
    "operation": "hoạt động; vận hành",
    "procedure": "thủ tục",
    "technique": "kỹ thuật",
    "technology": "công nghệ",
    "equipment": "thiết bị",
    "apparatus": "thiết bị; máy móc",
    "mechanism": "cơ chế",
    "specification": "thông số kỹ thuật",
    "standard": "tiêu chuẩn",
    "capacity": "năng lực; sức chứa",
    "performance": "hiệu suất; biểu diễn",
    "efficiency": "hiệu quả",
    "effectiveness": "hiệu quả",
    "accuracy": "độ chính xác",
    "quality": "chất lượng",
    "quantity": "số lượng",
    "density": "mật độ",
    "pressure": "áp suất",
    "temperature": "nhiệt độ",
    "speed": "tốc độ",
    "velocity": "vận tốc",
    "weight": "trọng lượng",
    "volume": "khối lượng; âm lượng",
    "area": "diện tích; khu vực",
    "length": "chiều dài",
    "width": "chiều rộng",
    "height": "chiều cao",
    "depth": "chiều sâu",
    "distance": "khoảng cách",
    "angle": "góc",
    "degree": "độ",
    "percentage": "phần trăm",
    "ratio": "tỷ lệ",
    "average": "trung bình",
    "total": "tổng",
    "sum": "tổng số",
    "difference": "sự khác biệt",
    "balance": "cân bằng; số dư",
    "profit": "lợi nhuận",
    "loss (financial)": "lỗ",
    "interest": "lãi suất; sự quan tâm",
    "investment": "đầu tư",
    "trade": "thương mại",
    "market": "thị trường",
    "economy": "kinh tế",
    "industry": "công nghiệp",
    "agriculture": "nông nghiệp",
    "manufacturing": "sản xuất",
    "construction": "xây dựng",
    "transportation": "vận chuyển",
    "communication": "giao tiếp; truyền thông",
    "network": "mạng lưới",
    "internet": "internet",
    "software": "phần mềm",
    "hardware": "phần cứng",
    "data": "dữ liệu",
    "file": "tệp; hồ sơ",
    "system": "hệ thống",
    "program": "chương trình",
    "application": "ứng dụng",
    "interface": "giao diện",
    "function": "chức năng",
    "button": "nút",
    "screen": "màn hình",
    "display": "hiển thị",
    "monitor": "màn hình",
    "keyboard": "bàn phím",
    "mouse": "chuột",
    "printer": "máy in",
    "scanner": "máy quét",
    "cable": "cáp",
    "battery": "pin",
    "charger": "bộ sạc",
    "power": "điện; sức mạnh",
    "signal": "tín hiệu",
    "channel": "kênh",
    "frequency": "tần số",
    "wave": "sóng",
    "current": "dòng điện; hiện tại",
    "voltage": "điện áp",
    "circuit": "mạch điện",
    "switch": "công tắc",
    "valve": "van",
    "pipe": "ống",
    "tube": "ống",
    "wire": "dây",
    "rope": "dây thừng",
    "chain": "dây xích",
    "spring": "lò xo; mùa xuân; suối",
    "gear": "bánh răng",
    "engine": "động cơ",
    "motor": "động cơ",
    "pump": "bơm",
    "fan": "quạt; người hâm mộ",
    "filter": "bộ lọc",
    "sensor": "cảm biến",
    "meter": "đồng hồ đo; mét",
    "gauge": "đồng hồ đo",
    "timer": "bộ hẹn giờ",
    "alarm": "báo động; chuông báo",
    "control": "điều khiển; kiểm soát",
    "remote control": "điều khiển từ xa",
    "radio": "radio",
    "television": "truyền hình",
    "broadcasting": "phát sóng",
    "recording": "ghi âm; ghi hình",
    "photograph": "ảnh; chụp ảnh",
    "photography": "nhiếp ảnh",
    "image": "hình ảnh",
    "picture": "bức tranh; ảnh",
    "painting": "tranh; sơn",
    "drawing": "bản vẽ; vẽ",
    "sketch": "phác thảo",
    "design": "thiết kế",
    "decoration": "trang trí",
    "fashion": "thời trang",
    "clothing": "quần áo",
    "fabric": "vải",
    "material": "vật liệu",
    "wood": "gỗ",
    "metal": "kim loại",
    "steel": "thép",
    "iron": "sắt",
    "copper": "đồng",
    "gold": "vàng",
    "silver": "bạc",
    "stone": "đá",
    "glass": "kính; thủy tinh",
    "plastic": "nhựa",
    "rubber": "cao su",
    "leather": "da",
    "paper": "giấy",
    "cardboard": "bìa cứng",
    "cotton": "bông",
    "silk": "lụa",
    "wool": "len",
    "thread": "chỉ; sợi",
    "needle": "kim",
    "scissors": "kéo",
    "knife": "dao",
    "fork": "dĩa",
    "spoon": "thìa",
    "chopsticks": "đũa",
    "plate": "đĩa",
    "bowl": "bát; tô",
    "cup": "cốc",
    "bottle": "chai",
    "box": "hộp",
    "bag": "túi",
    "basket": "giỏ",
    "container": "thùng chứa",
    "pot": "nồi",
    "pan": "chảo",
    "oven": "lò nướng",
    "refrigerator": "tủ lạnh",
    "furniture": "đồ nội thất",
    "table": "bàn",
    "chair": "ghế",
    "bed": "giường",
    "sofa": "ghế sofa",
    "shelf": "giá sách",
    "door": "cửa",
    "window": "cửa sổ",
    "wall": "tường",
    "floor": "sàn",
    "ceiling": "trần",
    "roof": "mái nhà",
    "garden": "vườn",
    "park": "công viên",
    "street": "đường phố",
    "bridge": "cây cầu",
    "station": "ga; trạm",
    "airport": "sân bay",
    "harbor": "cảng",
    "hospital": "bệnh viện",
    "clinic": "phòng khám",
    "pharmacy": "nhà thuốc",
    "bank": "ngân hàng",
    "post office": "bưu điện",
    "restaurant": "nhà hàng",
    "hotel": "khách sạn",
    "museum": "bảo tàng",
    "library": "thư viện",
    "theater": "rạp hát",
    "cinema": "rạp chiếu phim",
    "temple": "chùa; đền",
    "shrine": "đền thờ",
    "church": "nhà thờ",
    "castle": "lâu đài",
    "palace": "cung điện",
    "tower": "tháp",
    "stairs": "cầu thang",
    "elevator": "thang máy",
    "entrance": "lối vào",
    "exit": "lối ra",
    "parking": "bãi đậu xe",
    "traffic": "giao thông",
    "accident": "tai nạn",
    "emergency": "khẩn cấp",
    "police": "cảnh sát",
    "fire": "lửa; cháy",
    "medicine": "thuốc; y học",
    "treatment": "điều trị",
    "surgery": "phẫu thuật",
    "therapy": "liệu pháp",
    "symptom": "triệu chứng",
    "disease": "bệnh",
    "illness": "bệnh",
    "injury": "vết thương",
    "health": "sức khỏe",
    "diet": "chế độ ăn",
    "exercise": "tập thể dục",
    "sports": "thể thao",
    "competition": "cuộc thi",
    "tournament": "giải đấu",
    "championship": "giải vô địch",
    "record": "kỷ lục; hồ sơ",
    "score": "điểm số",
    "goal": "mục tiêu; bàn thắng",
    "victory": "chiến thắng",
    "defeat": "thất bại",
    "match": "trận đấu",
    "race": "cuộc đua",
    "marathon": "marathon",
    "swimming": "bơi lội",
    "running": "chạy",
    "jumping": "nhảy",
    "throwing": "ném",
    "football": "bóng đá",
    "baseball": "bóng chày",
    "basketball": "bóng rổ",
    "volleyball": "bóng chuyền",
    "tennis": "tennis",
    "golf": "golf",
    "boxing": "quyền anh",
    "martial arts": "võ thuật",
    "judo": "judo",
    "karate": "karate",
    "sumo": "sumo",
    "kendo": "kendo",
    "hiking": "đi bộ đường dài",
    "camping": "cắm trại",
    "fishing": "câu cá",
    "hunting": "săn bắn",
    "gardening": "làm vườn",
    "cooking": "nấu ăn",
    "baking": "nướng bánh",
    "sewing": "may vá",
    "knitting": "đan len",
    "painting": "vẽ; sơn",
    "writing": "viết",
    "reading": "đọc",
    "singing": "hát",
    "dancing": "nhảy múa",
    "acting": "diễn xuất",
    "directing": "đạo diễn",
    "producing": "sản xuất",
    "composition": "sáng tác; cấu tạo",
    "arrangement": "dàn dựng; sắp xếp",
    "performance": "biểu diễn",
    "concert": "buổi hòa nhạc",
    "exhibition": "triển lãm",
    "show": "buổi biểu diễn; chương trình",
    "event": "sự kiện",
    "festival": "lễ hội",
    "party": "bữa tiệc",
    "meeting": "cuộc họp",
    "conference": "hội nghị",
    "seminar": "hội thảo",
    "lecture": "bài giảng",
    "class": "lớp học",
    "lesson": "bài học",
    "homework": "bài tập về nhà",
    "exam": "kỳ thi",
    "test": "bài kiểm tra",
    "grade": "điểm; lớp",
    "graduation": "tốt nghiệp",
    "diploma": "bằng cấp",
    "degree (academic)": "bằng học thuật",
    "certificate": "chứng chỉ",
    "scholarship": "học bổng",
    "tuition": "học phí",
    "enrollment": "ghi danh",
    "application": "đơn xin; ứng dụng",
    "interview": "phỏng vấn",
    "employment": "việc làm",
    "salary": "lương",
    "promotion": "thăng tiến; khuyến mãi",
    "retirement": "nghỉ hưu",
    "vacation": "kỳ nghỉ",
    "holiday": "ngày lễ",
    "travel": "du lịch",
    "tourism": "du lịch",
    "trip": "chuyến đi",
    "journey": "hành trình",
    "adventure": "cuộc phiêu lưu",
    "scenery": "phong cảnh",
    "landscape": "cảnh quan",
    "view": "tầm nhìn; quan điểm",
    "sight": "cảnh; thị lực",
    "weather": "thời tiết",
    "climate": "khí hậu",
    "rain": "mưa",
    "snow": "tuyết",
    "wind": "gió",
    "sunshine": "ánh nắng",
    "cloud": "mây",
    "fog": "sương mù",
    "storm": "bão",
    "earthquake": "động đất",
    "volcano": "núi lửa",
    "flood": "lũ lụt",
    "drought": "hạn hán",
    "environment": "môi trường",
    "ecology": "sinh thái",
    "pollution": "ô nhiễm",
    "recycling": "tái chế",
    "energy": "năng lượng",
    "resource": "tài nguyên",
    "forest": "rừng",
    "river": "sông",
    "lake": "hồ",
    "ocean": "đại dương",
    "coast": "bờ biển",
    "island": "đảo",
    "peninsula": "bán đảo",
    "desert": "sa mạc",
    "plain": "đồng bằng",
    "valley": "thung lũng",
    "peak": "đỉnh núi",
    "cave": "hang động",
    "population": "dân số",
    "birth": "sự ra đời",
    "death": "cái chết",
    "marriage": "hôn nhân",
    "divorce": "ly hôn",
    "funeral": "đám tang",
    "religion": "tôn giáo",
    "belief": "niềm tin",
    "prayer": "lời cầu nguyện",
    "worship": "thờ phụng",
    "ceremony": "nghi lễ",
    "ritual": "nghi thức",
    "politics": "chính trị",
    "democracy": "dân chủ",
    "election": "bầu cử",
    "vote": "bỏ phiếu",
    "parliament": "nghị viện",
    "congress": "quốc hội",
    "president": "tổng thống",
    "prime minister": "thủ tướng",
    "minister": "bộ trưởng",
    "diplomat": "nhà ngoại giao",
    "treaty": "hiệp ước",
    "war": "chiến tranh",
    "peace": "hòa bình",
    "conflict": "xung đột",
    "negotiation": "đàm phán",
    "alliance": "liên minh",
    "sanction": "biện pháp trừng phạt",
    "economy": "kinh tế",
    "finance": "tài chính",
    "tax": "thuế",
    "budget": "ngân sách",
    "debt": "nợ",
    "inflation": "lạm phát",
    "unemployment": "thất nghiệp",
    "poverty": "nghèo đói",
    "welfare": "phúc lợi xã hội",
    "insurance": "bảo hiểm",
    "pension": "lương hưu",
    "charity": "từ thiện",
    "donation": "quyên góp",
    "volunteer": "tình nguyện viên",
    "cooperation": "sự hợp tác",
    "partnership": "quan hệ đối tác",
    "contract": "hợp đồng",
    "agreement (formal)": "thỏa thuận chính thức",
    "negotiation": "đàm phán",
    "compromise": "sự thỏa hiệp",
    "solution": "giải pháp",
    "alternative": "lựa chọn thay thế",
    "option": "lựa chọn",
    "priority": "ưu tiên",
    "strategy": "chiến lược",
    "tactic": "chiến thuật",
    "target": "mục tiêu",
    "schedule": "lịch trình",
    "deadline": "hạn chót",
    "progress": "tiến độ",
    "achievement": "thành tựu",
    "accomplishment": "hoàn thành",
    "contribution": "đóng góp",
    "participation": "sự tham gia",
    "involvement": "sự tham gia",
    "impact": "tác động",
    "feedback": "phản hồi",
    "evaluation": "đánh giá",
    "assessment": "đánh giá",
    "measurement": "đo lường",
    "survey": "khảo sát",
    "statistics": "thống kê",
    "data analysis": "phân tích dữ liệu",
    "forecast": "dự báo",
    "prediction": "dự đoán",
    "recommendation": "khuyến nghị",
    "proposal": "đề xuất",
    "report": "báo cáo",
    "presentation": "bài thuyết trình",
    "speech": "bài phát biểu",
    "debate": "tranh luận",
    "argument": "lý lẽ; tranh cãi",
    "opinion": "ý kiến",
    "view": "quan điểm",
    "perspective": "góc nhìn",
    "attitude": "thái độ",
    "approach": "cách tiếp cận",
    "concept": "khái niệm",
    "notion": "ý niệm",
    "assumption": "giả định",
    "hypothesis": "giả thuyết",
    "conclusion": "kết luận",
    "implication": "hàm ý",
    "consequence": "hậu quả",
    "outcome": "kết quả",

    # ------ greetings / interjections ------
    "yes": "vâng; có",
    "no": "không",
    "hello": "xin chào",
    "goodbye": "tạm biệt",
    "thank you": "cảm ơn",
    "welcome": "chào mừng",
    "excuse me": "xin lỗi",
    "sorry": "xin lỗi",
    "please": "xin hãy",
    "ok": "được",
    "okay": "được",
    "oh!": "ồ!",
    "oh dear!": "ôi trời!",
    "hey!": "này!",
    "well!": "ồ!",

    # ------ pronouns (when used as meanings) ------
    "I": "tôi",
    "you": "bạn; anh; chị; em",
    "he": "anh ấy; ông ấy",
    "she": "cô ấy; bà ấy",
    "it": "nó",
    "we": "chúng ta; chúng tôi",
    "they": "họ",
    "me": "tôi",
    "him": "anh ấy",
    "her": "cô ấy",
    "us": "chúng ta",
    "them": "họ",

    # ------ common compound / expressions ------
    "no good": "vô dụng",
    "good-for-nothing": "vô dụng",
    "not good": "không tốt",
    "nothing": "không có gì",
    "everything": "mọi thứ",
    "something": "điều gì đó",
    "someone": "ai đó",
    "anyone": "bất kỳ ai",
    "everyone": "mọi người",
    "all right": "được; ổn",
    "of course": "tất nhiên",
    "as a result": "kết quả là",
    "in general": "nói chung",
    "in particular": "đặc biệt",
    "in fact": "thực ra",
    "that is": "nghĩa là",
    "in other words": "nói cách khác",
    "so to speak": "có thể nói",
    "for example": "ví dụ",
    "lesser cuckoo (Cuculus poliocephalus)": "cu xám nhỏ (Cuculus poliocephalus)",
    "etc.": "v.v.",
    "etc.)": "v.v.",
    "chattering": "lải nhải; lắm mồm",
    "hesitantly": "do dự",
    "restlessly": "bồn chồn",
    "vigorously": "mạnh mẽ",
    "dawdling": "chần chừ; la cà",
}

# ---------------------------------------------------------------------------
# POS → Vietnamese label (for glosses)
# ---------------------------------------------------------------------------
POS_LABEL: dict[str, str] = {
    "n": "danh từ",
    "v1": "động từ nhóm 1",
    "v5u": "động từ nhóm 2",
    "v5k": "động từ nhóm 2",
    "v5g": "động từ nhóm 2",
    "v5s": "động từ nhóm 2",
    "v5t": "động từ nhóm 2",
    "v5n": "động từ nhóm 2",
    "v5b": "động từ nhóm 2",
    "v5m": "động từ nhóm 2",
    "v5r": "động từ nhóm 2",
    "v5aru": "động từ nhóm 2",
    "v5k-s": "động từ nhóm 2",
    "v5uru": "động từ nhóm 2",
    "vs": "động từ する",
    "vs-i": "động từ する",
    "vs-s": "động từ する",
    "vk": "động từ くる",
    "vi": "nội động từ",
    "vt": "ngoại động từ",
    "adj-i": "tính từ -i",
    "adj-na": "tính từ -na",
    "adj-no": "tính từ の",
    "adj-t": "tính từ たる",
    "adj-f": "tính từ",
    "adv": "trạng từ",
    "adv-to": "trạng từ",
    "conj": "liên từ",
    "int": "thán từ",
    "prt": "trợ từ",
    "pn": "đại từ",
    "exp": "thành ngữ",
    "suf": "hậu tố",
    "pref": "tiền tố",
    "ctr": "đơn vị đếm",
    "num": "số từ",
}


def translate_phrase(text: str) -> str:
    """Translate a single English phrase/word to Vietnamese."""
    t = text.strip()
    if not t:
        return ""

    # Direct lookup (case-sensitive first, then lowercase)
    if t in EN_VI:
        return EN_VI[t]
    tl = t.lower()
    if tl in EN_VI:
        return EN_VI[tl]

    # Strip "to " prefix for verbs
    if tl.startswith("to "):
        rest = tl[3:]
        if rest in EN_VI:
            return EN_VI[rest]
        # reconstruct with "to"
        key = "to " + rest
        if key in EN_VI:
            return EN_VI[key]

    # Handle "... no good", "not ..." patterns
    if tl.startswith("not "):
        rest = tl[4:]
        vi = EN_VI.get(rest, "")
        if vi:
            return "không " + vi

    # Return original English if no translation found
    return t


def translate_meaning(meaning_en: str) -> str:
    """Translate a full meaning_en string (may contain semicolons) to Vietnamese."""
    if not meaning_en:
        return ""

    parts = [p.strip() for p in meaning_en.split(";")]
    translated = []
    seen = set()

    for part in parts:
        vi = translate_phrase(part)
        if vi and vi not in seen:
            seen.add(vi)
            translated.append(vi)

    # Limit to 3 meanings max
    return "; ".join(translated[:3])


def make_keywords(meaning_vi: str, word: str) -> list[str]:
    """Generate search keywords from the Vietnamese meaning."""
    if not meaning_vi:
        return []
    parts = [p.strip() for p in meaning_vi.split(";")]
    keywords = []
    for p in parts:
        if p and p not in keywords:
            keywords.append(p)
    # add word itself if it looks like a loanword (katakana-heavy)
    return keywords[:4]


def make_gloss(meaning_vi: str, meaning_en: str) -> list[dict]:
    """Generate meaning_vi_glosses from the Vietnamese meaning."""
    if not meaning_vi:
        return []
    parts = [p.strip() for p in meaning_vi.split(";")]
    return [{"index": 1, "meaning": "; ".join(parts), "examples": []}]


def translate_entry(entry: dict) -> dict:
    """Translate a single vocabulary entry."""
    word = entry.get("word", "")
    kana = entry.get("kana", "")
    senses_in = entry.get("senses", [])
    senses_out = []

    for sense in senses_in:
        meaning_en = sense.get("meaning_en", "") or ""
        meaning_vi = translate_meaning(meaning_en)

        # confidence based on whether we actually translated
        if not meaning_vi:
            meaning_vi = meaning_en  # fallback
            confidence = "low"
        else:
            # check if translation actually happened (not just returned English)
            vi_parts = [p.strip() for p in meaning_vi.split(";")]
            en_parts = [p.strip().lower() for p in meaning_en.split(";")]
            translated_count = sum(
                1 for vp in vi_parts
                if not any(vp.lower() == ep for ep in en_parts)
            )
            if translated_count == 0:
                confidence = "low"
            elif translated_count < len(vi_parts):
                confidence = "medium"
            else:
                confidence = "high"

        senses_out.append({
            "sense_id": sense["sense_id"],
            "meaning_vi": meaning_vi,
            "confidence": confidence,
            "search_keywords": make_keywords(meaning_vi, word),
            "meaning_vi_glosses": make_gloss(meaning_vi, meaning_en),
        })

    return {
        "vocabulary_id": entry["vocabulary_id"],
        "word": word,
        "kana": kana,
        "senses": senses_out,
    }


def batch_number_to_filename(n: int) -> str:
    """Convert batch number to output filename matching existing naming convention."""
    # Convention seen: batch-00001 (5 zeros+1), batch-000010 (5 zeros+2 digits), etc.
    # The pattern is: "batch-" + zero-padded to (4 + digits) chars
    digits = len(str(n))
    pad = 4 + digits
    return f"batch-{str(n).zfill(pad)}.json"


def get_done_vocab_ids() -> set[int]:
    """Return set of vocabulary_ids already present in translated folder."""
    done = set()
    for fpath in glob.glob(os.path.join(OUTPUT_DIR, "*.json")):
        try:
            with open(fpath) as fp:
                raw = json.load(fp)
            entries = raw if isinstance(raw, list) else raw.get("data", [])
            for e in entries:
                if isinstance(e, dict):
                    done.add(e["vocabulary_id"])
        except Exception:
            pass
    return done


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Parse args
    all_batch_files = sorted(glob.glob(os.path.join(ENTRY_DIR, "entry-batch-*.json")))
    total = len(all_batch_files)

    if len(sys.argv) >= 3:
        start = int(sys.argv[1])
        end = int(sys.argv[2])
    elif len(sys.argv) == 2:
        start = int(sys.argv[1])
        end = total
    else:
        start = 1
        end = total

    print(f"Processing entry-batches {start}–{end} of {total}")

    done_vocab_ids = get_done_vocab_ids()
    print(f"Already translated: {len(done_vocab_ids)} vocab entries")

    processed = 0
    skipped = 0
    written = 0

    for batch_num in range(start, end + 1):
        fname = f"entry-batch-{str(batch_num).zfill(5)}.json"
        fpath = os.path.join(ENTRY_DIR, fname)

        if not os.path.exists(fpath):
            continue

        with open(fpath) as fp:
            entries = json.load(fp)

        # Skip if all entries in this batch already translated
        batch_vocab_ids = {e["vocabulary_id"] for e in entries}
        if batch_vocab_ids.issubset(done_vocab_ids):
            skipped += 1
            continue

        # Translate
        translated = [translate_entry(e) for e in entries]

        # Write output
        out_fname = batch_number_to_filename(batch_num)
        out_path = os.path.join(OUTPUT_DIR, out_fname)
        with open(out_path, "w", encoding="utf-8") as fp:
            json.dump(translated, fp, ensure_ascii=False, indent=2)

        processed += 1
        written += len(translated)

        if processed % 100 == 0:
            print(f"  [{processed}] Written {out_fname} ({written} entries so far)")

    print(f"\nDone.")
    print(f"Batches written: {processed}")
    print(f"Batches skipped (already done): {skipped}")
    print(f"Entries translated: {written}")


if __name__ == "__main__":
    main()
