export * from "./vocabulary.repository"
export * from "./related-vocabulary.repository"
export * from "./search-vocabulary.repository"
export * from "./vocabulary-relation.repository"
export * from "./vocabulary-collocation.repository"